# Generated by Django 5.1.7 on 2025-08-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topics',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='categories.category'),
        ),
        migrations.CreateModel(
            name='RelatedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topics', to='categories.category')),
                ('from_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='topics.topic')),
                ('to_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='topics.topic')),
            ],
        ),
    ]
